# Generated by Django 4.1 on 2022-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.CharField(default='njnjj', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
