# Generated by Django 4.1 on 2022-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
