# Generated by Django 4.1 on 2022-08-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0002_video_photo_video_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
    ]
