# Generated by Django 4.1 on 2022-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0002_alter_manage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='manage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
