# Generated by Django 4.1 on 2022-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0002_rename_video_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='manage',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
