# Generated by Django 4.1 on 2022-08-23 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0003_remove_video_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='video',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='type_menu', to='youtube_downloader.category'),
            preserve_default=False,
        ),
    ]
