# Generated by Django 4.1 on 2022-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0003_manage_content_alter_manage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
