# Generated by Django 4.1 on 2022-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0004_alter_manage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
