# Generated by Django 4.1 on 2022-08-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_downloader', '0005_alter_manage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage',
            name='content',
        ),
    ]
